unique_ids:
  assets:
    standard-page.html: V6PZHEUYP3OLLF6MMTB4VUV4BWULLNPN
    theme.css: 5JLHNUNKKLOLNM2VAX45UNEKR7OTSSY6
  forms:
    Form1: QYVIL3FVNLB5GCIMKKLX3LRSX7KQP2TQ
  modules: {}
  scripts: {}
  server_modules: {}
